// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
)

type AuditLog struct {
	ID              uuid.UUID
	EntityType      string
	EntityID        uuid.UUID
	ActionType      string
	FieldName       *string
	OldValue        *string
	NewValue        *string
	PerformedByID   uuid.UUID
	PerformedByName string
	CreatedOn       time.Time
}

type ChangeControl struct {
	ID                           uuid.UUID
	CcNumber                     int64
	CcID                         string
	CurrentState                 string
	ChangeOwnerID                uuid.UUID
	LastUpdatedByID              uuid.UUID
	CreatedOn                    time.Time
	LastUpdatedOn                time.Time
	ChangeTitle                  *string
	ChangeDescription            *string
	ChangeType                   *string
	ChangeCategory               *string
	DepartmentFunction           *string
	AffectedSystemsModules       *string
	ProposedImplementationDate   *time.Time
	TargetClosureDate            *time.Time
	ImplementationWindowStart    *time.Time
	ImplementationWindowEnd      *time.Time
	ReasonForChange              *string
	BusinessImpact               *string
	ExpectedDowntime             *string
	RequiresTesting              *string
	RequiresTraining             *string
	RiskRationale                *string
	KeyRisksMitigations          *string
	HighLevelImplementationPlan  *string
	ValidationApproach           *string
	SuccessCriteria              *string
	RollbackBackoutPlan          *string
	ActualImplementationDate     *time.Time
	PostImplementationIssues     *string
	ImplementationSummary        *string
	DeviationsFromPlan           *string
	ValidationPerformed          *string
	AssignedApproverID           *uuid.UUID
	CommentsForApprover          *string
	Decision                     *string
	RiskLevel                    *string
	DecisionComments             *string
	ImplementationApprovalByID   *uuid.UUID
	ImplementationApprovalOn     *time.Time
	FinalDecision                *string
	FinalComments                *string
	FinalApprovalByID            *uuid.UUID
	FinalApprovalOn              *time.Time
	ImplementationApprovalStatus string
	FinalApprovalStatus          string
	ActualClosureDate            *time.Time
	Comments                     *string
	CancellationReason           *string
}

type Esignature struct {
	ID              uuid.UUID
	ChangeControlID uuid.UUID
	SignerID        uuid.UUID
	SignerName      string
	Transition      string
	Meaning         string
	SignedOn        time.Time
}

type FileAttachment struct {
	ID              uuid.UUID
	ChangeControlID uuid.UUID
	FieldName       string
	FileName        string
	FileData        []byte
	ContentType     string
	FileSize        int64
	UploadedByID    uuid.UUID
	UploadedOn      time.Time
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	CreatedOn time.Time
	UpdatedOn time.Time
	ExpiresAt time.Time
	RevokedAt *time.Time
}

type User struct {
	ID             uuid.UUID
	FullName       string
	Email          string
	HashedPassword string
	Role           string
	IsActive       bool
	CreatedOn      time.Time
	UpdatedOn      time.Time
}
