// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (full_name, email, hashed_password, role)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, full_name, email, hashed_password, role, is_active, created_on, updated_on
`

type CreateUserParams struct {
	FullName       string
	Email          string
	HashedPassword string
	Role           string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FullName,
		arg.Email,
		arg.HashedPassword,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.IsActive,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, email, hashed_password, role, is_active, created_on, updated_on FROM users
WHERE LOWER(email) = LOWER($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.HashedPassword,
		&i.Role,
		&i.IsActive,
		&i.CreatedOn,
		&i.UpdatedOn,
	)
	return i, err
}
